{% set name = "MacFSEvents" %}
{% set version = "0.8.2" %}
{% set sha256 = "dd817434c612b838b89beaba419d477f5634d64455cf32ff5dc76cb26dd40ff7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not osx]
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fsevents

about:
  home: https://github.com/malthe/macfsevents
  license: BSD-2-Clause
  license_family: BSD
  # License is available in upstream repo, but not in PyPi Wheel.
  # Manually packaging it per https://conda-forge.org/docs/meta.html#packaging-the-license-manually
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: Thread-based interface to file system observation primitives.
  description: "MacFSEvents is a Python library that provides thread-safe directory observation primitives using callbacks. It wraps the Mac OS X FSEvents API in a C-extension.\nRequirements:\nMac OS X 10.5+ (Leopard) Python 2.7+\nThis software was written by Malthe Borch <mborch@gmail.com>. The pyfsevents module by Nicolas
    Dumazet was used for reference."
  doc_url: https://github.com/malthe/macfsevents
  dev_url: https://github.com/malthe/macfsevents

extra:
  recipe-maintainers:
    - pbronez
