appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: e2hiLV5xXJeqYD3RPgI09QHDMgQevf1SNByqwL1mBsdyE8lsQB7pnioVVturcDkNYq4mD+B8w/20jyKD+drZbCVllf2gGh/Adr/BE9jp8O8vEG3pVfONbIrIcbUrWzEkvKmWHxJCXh9FvTXD572IG6oPtOeR0BtkkvL74W31N4SjTMsgt9WlintLgixUkk6Y+VGYhYixePccG4mBBz+LJtNiSYUv3YnotKHiVh4XgOyLWKWawFpsUYTGK+H2W1syt6WrpEiHetAASyEfAmP4IeFkiRLk1OgMWG/+fgS3gIJ5/Vu6oRigWWTURQR5yrhEaKHahj0C+sLpH+tEzp4T/fXgi+FmzuvlFGBOpAxgXlOq7V4Fm7x6gMZSn9n4qt59Juaaxp/hEbBWreiXguNyb3XOZM0h3jOpCggi4gHhewfx2YFIBEVHWG3Q72+JsVFDk+sjdm7bUMQci84x/qWckVTqvU94h/9BZ+rrA1I6kelCdugZ8aLqVebzxoFFX8QGUjTgfybDO7kKX7S5aNJB3FzJGPdKf5uG9EOpRHxIrZpKE+zc1wNPTTfgKlt4UNj5gyGWLD/Nz1spUytA49QxG+9h40kJB6BEd71IVFHtrI73vCWs7VEnvNBGQmKVvD2gtkq202Vv2FydUXvQnj9O1fGYsPya7Kjxb8915EJYqKA=}
conda_forge_output_validation: true
